# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Projects/C/altv-lua-module

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Projects/C/altv-lua-module

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Projects/C/altv-lua-module/CMakeFiles /mnt/d/Projects/C/altv-lua-module/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Projects/C/altv-lua-module/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lua-module

# Build rule for target.
lua-module: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lua-module
.PHONY : lua-module

# fast build rule for target.
lua-module/fast:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/build
.PHONY : lua-module/fast

src/CLuaDefs.o: src/CLuaDefs.cpp.o

.PHONY : src/CLuaDefs.o

# target to build an object file
src/CLuaDefs.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CLuaDefs.cpp.o
.PHONY : src/CLuaDefs.cpp.o

src/CLuaDefs.i: src/CLuaDefs.cpp.i

.PHONY : src/CLuaDefs.i

# target to preprocess a source file
src/CLuaDefs.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CLuaDefs.cpp.i
.PHONY : src/CLuaDefs.cpp.i

src/CLuaDefs.s: src/CLuaDefs.cpp.s

.PHONY : src/CLuaDefs.s

# target to generate assembly for a file
src/CLuaDefs.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CLuaDefs.cpp.s
.PHONY : src/CLuaDefs.cpp.s

src/CLuaFunctionDefs.o: src/CLuaFunctionDefs.cpp.o

.PHONY : src/CLuaFunctionDefs.o

# target to build an object file
src/CLuaFunctionDefs.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CLuaFunctionDefs.cpp.o
.PHONY : src/CLuaFunctionDefs.cpp.o

src/CLuaFunctionDefs.i: src/CLuaFunctionDefs.cpp.i

.PHONY : src/CLuaFunctionDefs.i

# target to preprocess a source file
src/CLuaFunctionDefs.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CLuaFunctionDefs.cpp.i
.PHONY : src/CLuaFunctionDefs.cpp.i

src/CLuaFunctionDefs.s: src/CLuaFunctionDefs.cpp.s

.PHONY : src/CLuaFunctionDefs.s

# target to generate assembly for a file
src/CLuaFunctionDefs.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CLuaFunctionDefs.cpp.s
.PHONY : src/CLuaFunctionDefs.cpp.s

src/CLuaResourceImpl.o: src/CLuaResourceImpl.cpp.o

.PHONY : src/CLuaResourceImpl.o

# target to build an object file
src/CLuaResourceImpl.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CLuaResourceImpl.cpp.o
.PHONY : src/CLuaResourceImpl.cpp.o

src/CLuaResourceImpl.i: src/CLuaResourceImpl.cpp.i

.PHONY : src/CLuaResourceImpl.i

# target to preprocess a source file
src/CLuaResourceImpl.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CLuaResourceImpl.cpp.i
.PHONY : src/CLuaResourceImpl.cpp.i

src/CLuaResourceImpl.s: src/CLuaResourceImpl.cpp.s

.PHONY : src/CLuaResourceImpl.s

# target to generate assembly for a file
src/CLuaResourceImpl.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CLuaResourceImpl.cpp.s
.PHONY : src/CLuaResourceImpl.cpp.s

src/CLuaScriptRuntime.o: src/CLuaScriptRuntime.cpp.o

.PHONY : src/CLuaScriptRuntime.o

# target to build an object file
src/CLuaScriptRuntime.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CLuaScriptRuntime.cpp.o
.PHONY : src/CLuaScriptRuntime.cpp.o

src/CLuaScriptRuntime.i: src/CLuaScriptRuntime.cpp.i

.PHONY : src/CLuaScriptRuntime.i

# target to preprocess a source file
src/CLuaScriptRuntime.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CLuaScriptRuntime.cpp.i
.PHONY : src/CLuaScriptRuntime.cpp.i

src/CLuaScriptRuntime.s: src/CLuaScriptRuntime.cpp.s

.PHONY : src/CLuaScriptRuntime.s

# target to generate assembly for a file
src/CLuaScriptRuntime.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CLuaScriptRuntime.cpp.s
.PHONY : src/CLuaScriptRuntime.cpp.s

src/CVehModels.o: src/CVehModels.cpp.o

.PHONY : src/CVehModels.o

# target to build an object file
src/CVehModels.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CVehModels.cpp.o
.PHONY : src/CVehModels.cpp.o

src/CVehModels.i: src/CVehModels.cpp.i

.PHONY : src/CVehModels.i

# target to preprocess a source file
src/CVehModels.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CVehModels.cpp.i
.PHONY : src/CVehModels.cpp.i

src/CVehModels.s: src/CVehModels.cpp.s

.PHONY : src/CVehModels.s

# target to generate assembly for a file
src/CVehModels.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CVehModels.cpp.s
.PHONY : src/CVehModels.cpp.s

src/CVehMods.o: src/CVehMods.cpp.o

.PHONY : src/CVehMods.o

# target to build an object file
src/CVehMods.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CVehMods.cpp.o
.PHONY : src/CVehMods.cpp.o

src/CVehMods.i: src/CVehMods.cpp.i

.PHONY : src/CVehMods.i

# target to preprocess a source file
src/CVehMods.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CVehMods.cpp.i
.PHONY : src/CVehMods.cpp.i

src/CVehMods.s: src/CVehMods.cpp.s

.PHONY : src/CVehMods.s

# target to generate assembly for a file
src/CVehMods.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/CVehMods.cpp.s
.PHONY : src/CVehMods.cpp.s

src/Defs/CLuaAltFuncDefs.o: src/Defs/CLuaAltFuncDefs.cpp.o

.PHONY : src/Defs/CLuaAltFuncDefs.o

# target to build an object file
src/Defs/CLuaAltFuncDefs.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/CLuaAltFuncDefs.cpp.o
.PHONY : src/Defs/CLuaAltFuncDefs.cpp.o

src/Defs/CLuaAltFuncDefs.i: src/Defs/CLuaAltFuncDefs.cpp.i

.PHONY : src/Defs/CLuaAltFuncDefs.i

# target to preprocess a source file
src/Defs/CLuaAltFuncDefs.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/CLuaAltFuncDefs.cpp.i
.PHONY : src/Defs/CLuaAltFuncDefs.cpp.i

src/Defs/CLuaAltFuncDefs.s: src/Defs/CLuaAltFuncDefs.cpp.s

.PHONY : src/Defs/CLuaAltFuncDefs.s

# target to generate assembly for a file
src/Defs/CLuaAltFuncDefs.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/CLuaAltFuncDefs.cpp.s
.PHONY : src/Defs/CLuaAltFuncDefs.cpp.s

src/Defs/CLuaMiscScripts.o: src/Defs/CLuaMiscScripts.cpp.o

.PHONY : src/Defs/CLuaMiscScripts.o

# target to build an object file
src/Defs/CLuaMiscScripts.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/CLuaMiscScripts.cpp.o
.PHONY : src/Defs/CLuaMiscScripts.cpp.o

src/Defs/CLuaMiscScripts.i: src/Defs/CLuaMiscScripts.cpp.i

.PHONY : src/Defs/CLuaMiscScripts.i

# target to preprocess a source file
src/Defs/CLuaMiscScripts.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/CLuaMiscScripts.cpp.i
.PHONY : src/Defs/CLuaMiscScripts.cpp.i

src/Defs/CLuaMiscScripts.s: src/Defs/CLuaMiscScripts.cpp.s

.PHONY : src/Defs/CLuaMiscScripts.s

# target to generate assembly for a file
src/Defs/CLuaMiscScripts.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/CLuaMiscScripts.cpp.s
.PHONY : src/Defs/CLuaMiscScripts.cpp.s

src/Defs/CLuaRGBADefs.o: src/Defs/CLuaRGBADefs.cpp.o

.PHONY : src/Defs/CLuaRGBADefs.o

# target to build an object file
src/Defs/CLuaRGBADefs.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/CLuaRGBADefs.cpp.o
.PHONY : src/Defs/CLuaRGBADefs.cpp.o

src/Defs/CLuaRGBADefs.i: src/Defs/CLuaRGBADefs.cpp.i

.PHONY : src/Defs/CLuaRGBADefs.i

# target to preprocess a source file
src/Defs/CLuaRGBADefs.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/CLuaRGBADefs.cpp.i
.PHONY : src/Defs/CLuaRGBADefs.cpp.i

src/Defs/CLuaRGBADefs.s: src/Defs/CLuaRGBADefs.cpp.s

.PHONY : src/Defs/CLuaRGBADefs.s

# target to generate assembly for a file
src/Defs/CLuaRGBADefs.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/CLuaRGBADefs.cpp.s
.PHONY : src/Defs/CLuaRGBADefs.cpp.s

src/Defs/CLuaResourceFuncDefs.o: src/Defs/CLuaResourceFuncDefs.cpp.o

.PHONY : src/Defs/CLuaResourceFuncDefs.o

# target to build an object file
src/Defs/CLuaResourceFuncDefs.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/CLuaResourceFuncDefs.cpp.o
.PHONY : src/Defs/CLuaResourceFuncDefs.cpp.o

src/Defs/CLuaResourceFuncDefs.i: src/Defs/CLuaResourceFuncDefs.cpp.i

.PHONY : src/Defs/CLuaResourceFuncDefs.i

# target to preprocess a source file
src/Defs/CLuaResourceFuncDefs.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/CLuaResourceFuncDefs.cpp.i
.PHONY : src/Defs/CLuaResourceFuncDefs.cpp.i

src/Defs/CLuaResourceFuncDefs.s: src/Defs/CLuaResourceFuncDefs.cpp.s

.PHONY : src/Defs/CLuaResourceFuncDefs.s

# target to generate assembly for a file
src/Defs/CLuaResourceFuncDefs.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/CLuaResourceFuncDefs.cpp.s
.PHONY : src/Defs/CLuaResourceFuncDefs.cpp.s

src/Defs/CLuaVector3Defs.o: src/Defs/CLuaVector3Defs.cpp.o

.PHONY : src/Defs/CLuaVector3Defs.o

# target to build an object file
src/Defs/CLuaVector3Defs.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/CLuaVector3Defs.cpp.o
.PHONY : src/Defs/CLuaVector3Defs.cpp.o

src/Defs/CLuaVector3Defs.i: src/Defs/CLuaVector3Defs.cpp.i

.PHONY : src/Defs/CLuaVector3Defs.i

# target to preprocess a source file
src/Defs/CLuaVector3Defs.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/CLuaVector3Defs.cpp.i
.PHONY : src/Defs/CLuaVector3Defs.cpp.i

src/Defs/CLuaVector3Defs.s: src/Defs/CLuaVector3Defs.cpp.s

.PHONY : src/Defs/CLuaVector3Defs.s

# target to generate assembly for a file
src/Defs/CLuaVector3Defs.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/CLuaVector3Defs.cpp.s
.PHONY : src/Defs/CLuaVector3Defs.cpp.s

src/Defs/Entity/CLuaBaseObjectDefs.o: src/Defs/Entity/CLuaBaseObjectDefs.cpp.o

.PHONY : src/Defs/Entity/CLuaBaseObjectDefs.o

# target to build an object file
src/Defs/Entity/CLuaBaseObjectDefs.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaBaseObjectDefs.cpp.o
.PHONY : src/Defs/Entity/CLuaBaseObjectDefs.cpp.o

src/Defs/Entity/CLuaBaseObjectDefs.i: src/Defs/Entity/CLuaBaseObjectDefs.cpp.i

.PHONY : src/Defs/Entity/CLuaBaseObjectDefs.i

# target to preprocess a source file
src/Defs/Entity/CLuaBaseObjectDefs.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaBaseObjectDefs.cpp.i
.PHONY : src/Defs/Entity/CLuaBaseObjectDefs.cpp.i

src/Defs/Entity/CLuaBaseObjectDefs.s: src/Defs/Entity/CLuaBaseObjectDefs.cpp.s

.PHONY : src/Defs/Entity/CLuaBaseObjectDefs.s

# target to generate assembly for a file
src/Defs/Entity/CLuaBaseObjectDefs.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaBaseObjectDefs.cpp.s
.PHONY : src/Defs/Entity/CLuaBaseObjectDefs.cpp.s

src/Defs/Entity/CLuaBlipDefs.o: src/Defs/Entity/CLuaBlipDefs.cpp.o

.PHONY : src/Defs/Entity/CLuaBlipDefs.o

# target to build an object file
src/Defs/Entity/CLuaBlipDefs.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaBlipDefs.cpp.o
.PHONY : src/Defs/Entity/CLuaBlipDefs.cpp.o

src/Defs/Entity/CLuaBlipDefs.i: src/Defs/Entity/CLuaBlipDefs.cpp.i

.PHONY : src/Defs/Entity/CLuaBlipDefs.i

# target to preprocess a source file
src/Defs/Entity/CLuaBlipDefs.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaBlipDefs.cpp.i
.PHONY : src/Defs/Entity/CLuaBlipDefs.cpp.i

src/Defs/Entity/CLuaBlipDefs.s: src/Defs/Entity/CLuaBlipDefs.cpp.s

.PHONY : src/Defs/Entity/CLuaBlipDefs.s

# target to generate assembly for a file
src/Defs/Entity/CLuaBlipDefs.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaBlipDefs.cpp.s
.PHONY : src/Defs/Entity/CLuaBlipDefs.cpp.s

src/Defs/Entity/CLuaCheckpointDefs.o: src/Defs/Entity/CLuaCheckpointDefs.cpp.o

.PHONY : src/Defs/Entity/CLuaCheckpointDefs.o

# target to build an object file
src/Defs/Entity/CLuaCheckpointDefs.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaCheckpointDefs.cpp.o
.PHONY : src/Defs/Entity/CLuaCheckpointDefs.cpp.o

src/Defs/Entity/CLuaCheckpointDefs.i: src/Defs/Entity/CLuaCheckpointDefs.cpp.i

.PHONY : src/Defs/Entity/CLuaCheckpointDefs.i

# target to preprocess a source file
src/Defs/Entity/CLuaCheckpointDefs.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaCheckpointDefs.cpp.i
.PHONY : src/Defs/Entity/CLuaCheckpointDefs.cpp.i

src/Defs/Entity/CLuaCheckpointDefs.s: src/Defs/Entity/CLuaCheckpointDefs.cpp.s

.PHONY : src/Defs/Entity/CLuaCheckpointDefs.s

# target to generate assembly for a file
src/Defs/Entity/CLuaCheckpointDefs.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaCheckpointDefs.cpp.s
.PHONY : src/Defs/Entity/CLuaCheckpointDefs.cpp.s

src/Defs/Entity/CLuaColShapeDefs.o: src/Defs/Entity/CLuaColShapeDefs.cpp.o

.PHONY : src/Defs/Entity/CLuaColShapeDefs.o

# target to build an object file
src/Defs/Entity/CLuaColShapeDefs.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaColShapeDefs.cpp.o
.PHONY : src/Defs/Entity/CLuaColShapeDefs.cpp.o

src/Defs/Entity/CLuaColShapeDefs.i: src/Defs/Entity/CLuaColShapeDefs.cpp.i

.PHONY : src/Defs/Entity/CLuaColShapeDefs.i

# target to preprocess a source file
src/Defs/Entity/CLuaColShapeDefs.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaColShapeDefs.cpp.i
.PHONY : src/Defs/Entity/CLuaColShapeDefs.cpp.i

src/Defs/Entity/CLuaColShapeDefs.s: src/Defs/Entity/CLuaColShapeDefs.cpp.s

.PHONY : src/Defs/Entity/CLuaColShapeDefs.s

# target to generate assembly for a file
src/Defs/Entity/CLuaColShapeDefs.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaColShapeDefs.cpp.s
.PHONY : src/Defs/Entity/CLuaColShapeDefs.cpp.s

src/Defs/Entity/CLuaEntityDefs.o: src/Defs/Entity/CLuaEntityDefs.cpp.o

.PHONY : src/Defs/Entity/CLuaEntityDefs.o

# target to build an object file
src/Defs/Entity/CLuaEntityDefs.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaEntityDefs.cpp.o
.PHONY : src/Defs/Entity/CLuaEntityDefs.cpp.o

src/Defs/Entity/CLuaEntityDefs.i: src/Defs/Entity/CLuaEntityDefs.cpp.i

.PHONY : src/Defs/Entity/CLuaEntityDefs.i

# target to preprocess a source file
src/Defs/Entity/CLuaEntityDefs.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaEntityDefs.cpp.i
.PHONY : src/Defs/Entity/CLuaEntityDefs.cpp.i

src/Defs/Entity/CLuaEntityDefs.s: src/Defs/Entity/CLuaEntityDefs.cpp.s

.PHONY : src/Defs/Entity/CLuaEntityDefs.s

# target to generate assembly for a file
src/Defs/Entity/CLuaEntityDefs.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaEntityDefs.cpp.s
.PHONY : src/Defs/Entity/CLuaEntityDefs.cpp.s

src/Defs/Entity/CLuaPlayerDefs.o: src/Defs/Entity/CLuaPlayerDefs.cpp.o

.PHONY : src/Defs/Entity/CLuaPlayerDefs.o

# target to build an object file
src/Defs/Entity/CLuaPlayerDefs.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaPlayerDefs.cpp.o
.PHONY : src/Defs/Entity/CLuaPlayerDefs.cpp.o

src/Defs/Entity/CLuaPlayerDefs.i: src/Defs/Entity/CLuaPlayerDefs.cpp.i

.PHONY : src/Defs/Entity/CLuaPlayerDefs.i

# target to preprocess a source file
src/Defs/Entity/CLuaPlayerDefs.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaPlayerDefs.cpp.i
.PHONY : src/Defs/Entity/CLuaPlayerDefs.cpp.i

src/Defs/Entity/CLuaPlayerDefs.s: src/Defs/Entity/CLuaPlayerDefs.cpp.s

.PHONY : src/Defs/Entity/CLuaPlayerDefs.s

# target to generate assembly for a file
src/Defs/Entity/CLuaPlayerDefs.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaPlayerDefs.cpp.s
.PHONY : src/Defs/Entity/CLuaPlayerDefs.cpp.s

src/Defs/Entity/CLuaVehicleDefs.o: src/Defs/Entity/CLuaVehicleDefs.cpp.o

.PHONY : src/Defs/Entity/CLuaVehicleDefs.o

# target to build an object file
src/Defs/Entity/CLuaVehicleDefs.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaVehicleDefs.cpp.o
.PHONY : src/Defs/Entity/CLuaVehicleDefs.cpp.o

src/Defs/Entity/CLuaVehicleDefs.i: src/Defs/Entity/CLuaVehicleDefs.cpp.i

.PHONY : src/Defs/Entity/CLuaVehicleDefs.i

# target to preprocess a source file
src/Defs/Entity/CLuaVehicleDefs.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaVehicleDefs.cpp.i
.PHONY : src/Defs/Entity/CLuaVehicleDefs.cpp.i

src/Defs/Entity/CLuaVehicleDefs.s: src/Defs/Entity/CLuaVehicleDefs.cpp.s

.PHONY : src/Defs/Entity/CLuaVehicleDefs.s

# target to generate assembly for a file
src/Defs/Entity/CLuaVehicleDefs.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaVehicleDefs.cpp.s
.PHONY : src/Defs/Entity/CLuaVehicleDefs.cpp.s

src/Defs/Entity/CLuaVoiceChannelDefs.o: src/Defs/Entity/CLuaVoiceChannelDefs.cpp.o

.PHONY : src/Defs/Entity/CLuaVoiceChannelDefs.o

# target to build an object file
src/Defs/Entity/CLuaVoiceChannelDefs.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaVoiceChannelDefs.cpp.o
.PHONY : src/Defs/Entity/CLuaVoiceChannelDefs.cpp.o

src/Defs/Entity/CLuaVoiceChannelDefs.i: src/Defs/Entity/CLuaVoiceChannelDefs.cpp.i

.PHONY : src/Defs/Entity/CLuaVoiceChannelDefs.i

# target to preprocess a source file
src/Defs/Entity/CLuaVoiceChannelDefs.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaVoiceChannelDefs.cpp.i
.PHONY : src/Defs/Entity/CLuaVoiceChannelDefs.cpp.i

src/Defs/Entity/CLuaVoiceChannelDefs.s: src/Defs/Entity/CLuaVoiceChannelDefs.cpp.s

.PHONY : src/Defs/Entity/CLuaVoiceChannelDefs.s

# target to generate assembly for a file
src/Defs/Entity/CLuaVoiceChannelDefs.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaVoiceChannelDefs.cpp.s
.PHONY : src/Defs/Entity/CLuaVoiceChannelDefs.cpp.s

src/Defs/Entity/CLuaWorldObjectDefs.o: src/Defs/Entity/CLuaWorldObjectDefs.cpp.o

.PHONY : src/Defs/Entity/CLuaWorldObjectDefs.o

# target to build an object file
src/Defs/Entity/CLuaWorldObjectDefs.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaWorldObjectDefs.cpp.o
.PHONY : src/Defs/Entity/CLuaWorldObjectDefs.cpp.o

src/Defs/Entity/CLuaWorldObjectDefs.i: src/Defs/Entity/CLuaWorldObjectDefs.cpp.i

.PHONY : src/Defs/Entity/CLuaWorldObjectDefs.i

# target to preprocess a source file
src/Defs/Entity/CLuaWorldObjectDefs.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaWorldObjectDefs.cpp.i
.PHONY : src/Defs/Entity/CLuaWorldObjectDefs.cpp.i

src/Defs/Entity/CLuaWorldObjectDefs.s: src/Defs/Entity/CLuaWorldObjectDefs.cpp.s

.PHONY : src/Defs/Entity/CLuaWorldObjectDefs.s

# target to generate assembly for a file
src/Defs/Entity/CLuaWorldObjectDefs.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Defs/Entity/CLuaWorldObjectDefs.cpp.s
.PHONY : src/Defs/Entity/CLuaWorldObjectDefs.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/lua-module.dir/build.make CMakeFiles/lua-module.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... lua-module"
	@echo "... edit_cache"
	@echo "... src/CLuaDefs.o"
	@echo "... src/CLuaDefs.i"
	@echo "... src/CLuaDefs.s"
	@echo "... src/CLuaFunctionDefs.o"
	@echo "... src/CLuaFunctionDefs.i"
	@echo "... src/CLuaFunctionDefs.s"
	@echo "... src/CLuaResourceImpl.o"
	@echo "... src/CLuaResourceImpl.i"
	@echo "... src/CLuaResourceImpl.s"
	@echo "... src/CLuaScriptRuntime.o"
	@echo "... src/CLuaScriptRuntime.i"
	@echo "... src/CLuaScriptRuntime.s"
	@echo "... src/CVehModels.o"
	@echo "... src/CVehModels.i"
	@echo "... src/CVehModels.s"
	@echo "... src/CVehMods.o"
	@echo "... src/CVehMods.i"
	@echo "... src/CVehMods.s"
	@echo "... src/Defs/CLuaAltFuncDefs.o"
	@echo "... src/Defs/CLuaAltFuncDefs.i"
	@echo "... src/Defs/CLuaAltFuncDefs.s"
	@echo "... src/Defs/CLuaMiscScripts.o"
	@echo "... src/Defs/CLuaMiscScripts.i"
	@echo "... src/Defs/CLuaMiscScripts.s"
	@echo "... src/Defs/CLuaRGBADefs.o"
	@echo "... src/Defs/CLuaRGBADefs.i"
	@echo "... src/Defs/CLuaRGBADefs.s"
	@echo "... src/Defs/CLuaResourceFuncDefs.o"
	@echo "... src/Defs/CLuaResourceFuncDefs.i"
	@echo "... src/Defs/CLuaResourceFuncDefs.s"
	@echo "... src/Defs/CLuaVector3Defs.o"
	@echo "... src/Defs/CLuaVector3Defs.i"
	@echo "... src/Defs/CLuaVector3Defs.s"
	@echo "... src/Defs/Entity/CLuaBaseObjectDefs.o"
	@echo "... src/Defs/Entity/CLuaBaseObjectDefs.i"
	@echo "... src/Defs/Entity/CLuaBaseObjectDefs.s"
	@echo "... src/Defs/Entity/CLuaBlipDefs.o"
	@echo "... src/Defs/Entity/CLuaBlipDefs.i"
	@echo "... src/Defs/Entity/CLuaBlipDefs.s"
	@echo "... src/Defs/Entity/CLuaCheckpointDefs.o"
	@echo "... src/Defs/Entity/CLuaCheckpointDefs.i"
	@echo "... src/Defs/Entity/CLuaCheckpointDefs.s"
	@echo "... src/Defs/Entity/CLuaColShapeDefs.o"
	@echo "... src/Defs/Entity/CLuaColShapeDefs.i"
	@echo "... src/Defs/Entity/CLuaColShapeDefs.s"
	@echo "... src/Defs/Entity/CLuaEntityDefs.o"
	@echo "... src/Defs/Entity/CLuaEntityDefs.i"
	@echo "... src/Defs/Entity/CLuaEntityDefs.s"
	@echo "... src/Defs/Entity/CLuaPlayerDefs.o"
	@echo "... src/Defs/Entity/CLuaPlayerDefs.i"
	@echo "... src/Defs/Entity/CLuaPlayerDefs.s"
	@echo "... src/Defs/Entity/CLuaVehicleDefs.o"
	@echo "... src/Defs/Entity/CLuaVehicleDefs.i"
	@echo "... src/Defs/Entity/CLuaVehicleDefs.s"
	@echo "... src/Defs/Entity/CLuaVoiceChannelDefs.o"
	@echo "... src/Defs/Entity/CLuaVoiceChannelDefs.i"
	@echo "... src/Defs/Entity/CLuaVoiceChannelDefs.s"
	@echo "... src/Defs/Entity/CLuaWorldObjectDefs.o"
	@echo "... src/Defs/Entity/CLuaWorldObjectDefs.i"
	@echo "... src/Defs/Entity/CLuaWorldObjectDefs.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

